name: Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2.5.1
      with:
        node-version: '12.x'

    - name: Build
      run: |
        yarn
        yarn build
        
    - name: Test
      run: yarn jest
